name: Release

on:
  push:
    branches:
      - release

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release
    uses: ./.github/workflows/_release.yml
    with:
      binary-name: hyprlay
      platforms: multi
      build-binaries: true
      publish-crates: false
      artifact-pattern: 'hyprlay*-*'
    secrets: inherit
